from .dialects.postgresql import create_versioning_trigger_listeners as create_versioning_trigger_listeners
from .model_builder import ModelBuilder as ModelBuilder
from .relationship_builder import RelationshipBuilder as RelationshipBuilder
from .table_builder import TableBuilder as TableBuilder

def prevent_reentry(handler): ...

class Builder:
    def build_triggers(self) -> None: ...
    def build_tables(self) -> None: ...
    def closest_matching_table(self, model): ...
    def build_models(self) -> None: ...
    def build_relationships(self, version_classes) -> None: ...
    def instrument_versioned_classes(self, mapper, cls) -> None: ...
    def build_transaction_class(self) -> None: ...
    def configure_versioned_classes(self) -> None: ...
    def enable_active_history(self, version_classes) -> None: ...
    def create_column_aliases(self, version_classes) -> None: ...
