from .utils import end_tx_column_name as end_tx_column_name, tx_column_name as tx_column_name
from _typeshed import Incomplete
from collections.abc import Generator

def parent_identity(obj_or_class): ...
def eqmap(callback, iterable) -> Generator[Incomplete, None, None]: ...
def parent_criteria(obj, class_: Incomplete | None = ...): ...

class VersionObjectFetcher:
    manager: Incomplete
    def __init__(self, manager) -> None: ...
    def previous(self, obj): ...
    def index(self, obj): ...
    def next(self, obj): ...

class SubqueryFetcher(VersionObjectFetcher):
    def previous_query(self, obj): ...
    def next_query(self, obj): ...

class ValidityFetcher(VersionObjectFetcher):
    def next_query(self, obj): ...
    def previous_query(self, obj): ...
