from _typeshed import Incomplete

def get_end_tx_column_query(table, end_tx_column_name: str = ..., tx_column_name: str = ...): ...
def update_end_tx_column(table, end_tx_column_name: str = ..., tx_column_name: str = ..., conn: Incomplete | None = ...) -> None: ...
def get_property_mod_flags_query(table, tracked_columns, mod_suffix: str = ..., end_tx_column_name: str = ..., tx_column_name: str = ...): ...
def update_property_mod_flags(table, tracked_columns, mod_suffix: str = ..., end_tx_column_name: str = ..., tx_column_name: str = ..., conn: Incomplete | None = ...) -> None: ...
