from ..utils import versioned_column_properties as versioned_column_properties
from .base import Plugin as Plugin

class PropertyModTrackerPlugin(Plugin):
    column_suffix: str
    def create_mod_column(self, column): ...
    def after_build_version_table_columns(self, table_builder, columns) -> None: ...
    def after_create_version_object(self, uow, parent_obj, version_obj) -> None: ...
    def after_construct_changeset(self, version_obj, changeset) -> None: ...
