from pathlib import Path

import typer

from .. import MODULE_PATH

cli = typer.Typer()


@cli.command()
def check(
    sqlalchemy_url="postgresql+asyncpg://postgres:postgres@localhost/hitfactorpy",
    alembic_dir: Path = MODULE_PATH / "migrations",
):
    """proxy for `alembic check`"""
    from alembic import command as alembic_command
    from alembic.config import Config as AlembicConfig
    from alembic.util.exc import AutogenerateDiffsDetected

    alembic_cfg = AlembicConfig()
    alembic_cfg.set_main_option("script_location", str(alembic_dir))
    alembic_cfg.set_main_option("sqlalchemy.url", sqlalchemy_url)
    try:
        alembic_command.check(alembic_cfg)
    except AutogenerateDiffsDetected as e:
        typer.echo(e)
        exit(1)
    typer.echo("OK: DB and code are in sync")


if __name__ == "__main__":
    cli()
